import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Sidebar from "@/components/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Modulo de Consultas",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="es"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-screen flex flex-col">
        {/*Encabezado del sitio */}
        <header className="w-full bg-[#A01C1B] text-white shadow-md">
          <div className="w-full px-.5 flex items-center justify-between">

            <div className="flex items-center gap-4">
              <Image
                src="/assets/LogoUaeh1.png"
                width={200}
                height={82}
                alt="logo"
              />
              <h1 className="text-4xl font-medium tracking-wide">
                Módulo de Consultas
              </h1>
            </div>

            <div className="flex items-center gap-3 px-5">
              <span className="text-4xl font-medium">3:34 PM</span>
              <span className="text-lg opacity-80">Jueves 19 marzo</span>
              <div className="w-8 h-8 rounded-full border flex items-center justify-center">
                <Image
                  src="/assets/acceso.png"
                  width={32}
                  height={32}
                  alt="Inicar Sesión"
                />
              </div>
              <span className="text-lg font-semibold">Iniciar Sesión</span>
            </div>

          </div>
        </header>

        {/*Menú lateral del sitio */}
        <div className="flex flex-1">
          <Sidebar />
          <main className="flex-1 bg-gray-100 p-6">
            {children}
          </main>

        </div>

      </body>
    </html>
  );
}
